### ISSUE TITLE
关于实验一中的LFM信号 HDL实现代码开源

### ISSUE THREAD

**Issue by yao-jiangyu** [Floyd-Fish/RadarSignalProcessing_experiment#1]
您好，想问一下LFM信号 HDL实现代码是否开源呢？想用于学习一下，万分期待您的回复！

**Comment by Floyd-Fish** [comment]
你好，我询问了原作者（CNPP），由于时间过于久远，这份代码他好像已经遗失了，很抱歉。
________________________________
发件人: 吃饭真的很重要 ***@***.***>
发送时间: 2024年7月4日 14:39
收件人: Floyd-Fish/RadarSignalProcessing_experiment ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Floyd-Fish/RadarSignalProcessing_experiment] 关于实验一中的LFM信号 HDL实现代码开源 (Issue #1)


您好，想问一下LFM信号 HDL实现代码是否开源呢？想用于学习一下，万分期待您的回复！

―
